### ISSUE TITLE
[Registro de conteúdo] - Adicionar o combobox do número da aula conforme tela de Registro de Frequência

### ISSUE THREAD

**Issue by marcosoliveirasoares94** [portabilis/i-diario#119]
**CONTEXTO:**

Por que esta alteração é importante?
Essa alteração permitiria que professores que trabalham na mesma turma com mais de uma aula e conteúdos diferentes pudessem realizar o lançamento do conteúdo expecífico para cada aula.

Como esta alteração pode beneficiar outros usuários?
Melhor clareza no lançamento do conteúdo de uma determinada aula e possível melhor gestão ao emitir um relatório de quantidade de aulas ministradas que não seja olhando pela frequência.

**IMPLEMENTAÇÃO:**

Acrescentar na tela de Registro de conteúdo a combobox do número da Aula, persistindo também essa informação em banco de dados no mesmo estilo da frequência.

**Comment by marcosoliveirasoares94** [comment]
@edersoares vamos discutir esse caso? Se for factível, a comunidade pode enviar esse PR!

**Comment by edersoares** [comment]
Marcando a @juliahrizzatti para entender se faz sentido, eu entendo que o professor em geral faz por dia o registro de conteúdo, mas talvez seja uma necessidade ser por aula.

**Comment by marcosoliveirasoares94** [comment]
> Marcando a @juliahrizzatti para entender se faz sentido, eu entendo que o professor em geral faz por dia o registro de conteúdo, mas talvez seja uma necessidade ser por aula.

Obrigado pelo direcionamento @edersoares.

Acredito que a parametrização seria o ideal, pois professores fazem por dia para turma/disciplina no entanto pode ocorrer de casos como os municípios do Piauí que professores pode lançar conteúdo por turma/disciplina porém no mesmo dia aula da mesma disciplina porém conteúdos diferentes.
