### ISSUE TITLE
Erro na sincronização de calendário letivo

### ISSUE THREAD

**Issue by msoares94** [portabilis/i-diario#162]
**MENU:**

[Início] -> [ Calendário letivo]

**DESCRIÇÃO:**

Por padrão o i-Diário obtém as datas para preenchimento do calendário letivo junto ao i-Educar e define no seu calendário letivo, respectivamente para cada escola configurada.

Data inicial e Data final como não editáveis, pois vem do i-Educar e defini Data Inicial para lançamentos e Data final para lançamentos como campos editáveis e que nesse primeiro momento repetem as datas obtidas do i-Educar

![image](https://github.com/portabilis/i-diario/assets/12193221/a319f9c5-4dc8-4a9b-a946-223edd01edcc)

Nessa branch atual, quando configura-se uma nova "Data final para lançamentos", o sistema aceita salvar os dados, porém, após uma sincronização a configuração volta para os valores default configurados no i-Educar, tal comportamento não ocorria na versão 1.4

**Comment by edersoares** [comment]
@msoares94 a data é posterior ao fim da etapa?

**Comment by msoares94** [comment]
> @msoares94 a data é posterior a "Data final" da etapa?

Sim @edersoares!

Na versão antiga isso não ocorria.

Vou colocar um print do i-Diário da versão 1.4 no qual aceitava datas após a data final do i-Educar.

![image](https://github.com/portabilis/i-diario/assets/12193221/a04f0598-37c5-4181-9dec-95fe8f56fcc4)

**Comment by edersoares** [comment]
@msoares94 essa regra está sendo repensada, mas por hora não é um erro, em tese, nenhum professor deveria lançar posteriormente ao encerramento de uma etapa.

Se isso é uma realidade para você, você pode alterar essa parte do código:

https://github.com/portabilis/i-diario/blob/1.5/app/services/ieducar_synchronizers/school_calendars_synchronizer.rb#L104-L114

**Comment by msoares94** [comment]
@edersoares entendo, porém como você mencionou que é uma regra que esta sendo repensada, não deveriam ter modificado ela nesse momento até termos uma clareza sobre o novo comportamento, bom, essa é minha forma de ver.

Até porque se modificaram o comportamento dela, já deveriam desabilitar a possibilidade de editar tais informações "Data inicial para lançamentos" e "data final para lançamentos"

De toda forma, sim, em tese deveria-se ter as informações lançadas em real-time, minha realidade e a realidade da comunidade não é essa, acaredito que da Portabilis também não. Trabalhamos com pessoas, e pessoas são suscetíveis a problemas e ficarem indispostas ao trabalho, ocasionando no atraso do lançamento dos registros.

Considero o fluxo antigo como o fluxo principal e caso os administradores decidissem bloquear o lançamento ai sim, ajustar nos parâmetros.

Outro ponto que não faz sentido terem modificado isso é que o padrão é o i-Diário preencher os dados de forma replicada, ou seja, ele preenche dos campos "Data inicial para lançamentos" e "data final para lançamentos" já com os valores do i-Educar e os administradores avaliam e identificam que é necessário ajsutar para a realidade de cada escola/município, logo, eles editam (seria já a parametrização) para permitir os lançamentos.


Sugiro rever o comportamento levando isso em consideração.
