### ISSUE TITLE
Registrando falta no feriado do carnaval

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-diario#20]
**MENU:**

Relatórios -> Registros de frequência -> < seleciona datas > -> Imprimir

**DESCRIÇÃO:**

O sistema está atribuindo faltas para os alunos nos dias do carnaval

**AMBIENTE:**

- Instalação direta
- Sistema operacional: Lubuntu 16.04 e i-Diário 1.0.3
- Navegador: Firefox

[registro-de-frequencia-e4df7fabd6946856918d387334410864.pdf](https://github.com/portabilis/i-diario/files/3004795/registro-de-frequencia-e4df7fabd6946856918d387334410864.pdf)
![2019-03-25-144224_1366x768_scrot](https://user-images.githubusercontent.com/20538912/54942539-114e6e80-4f0e-11e9-987f-e935d917a7c7.png)

**Comment by MarceloCajueiro** [comment]
O registro de falta foi feito antes ou depois do cadastro do calendário letivo?

Recomendo apagar o registro de falta e tentar lançar outra vez para a data bloqueada.

**Comment by robson-alcantara** [comment]
"O registro de falta foi feito antes ou depois do cadastro do calendário letivo?"
Foi feito após

O registro foi apagado, mas como lançar em uma data que não permite lançamentos?

**Comment by MarceloCajueiro** [comment]
Por isso a pergunta. Se não dá para lançar, está funcionando, não?

**Comment by seducflores** [comment]
Perdão amigo, você querendo ajudar e eu falando besteira. Consegui acessar a chamada no dia de carnaval, acho que não deveria permitir. No dia que fiz isso, removi a chamada

**Comment by MarceloCajueiro** [comment]
Certo! Vamos deixar o item aqui e ver se a comunidade resolve esse problema.

**Comment by robson-alcantara** [comment]
O problema era que especificamente o turno da aula não tinha sido escolhido
