### ISSUE TITLE
dry-inflector-0.2.0 precisa do ruby 2.4 e o projeto é 2.3.7

### ISSUE THREAD

**Issue by rsdevigo** [portabilis/i-diario#52]
Olá e obrigado por nos ajudar a tornar o i-Diário um projeto mais estável. Para
reportar seu bug use o template abaixo:

**DESCRIÇÃO:**

O erro é que não consigo instalar nem por docker e nem pela instalação direta, pois quando executo o bundle  install o mesmo tenta instalar a dependência dry-inflector-0.2.0 mas não consegue pois ele precisa do ruby 2.4 e o projeto é 2.3.7.

Só que atualizando o ruby e o projeto para 2.4 o bundle install funciona, mas começa a surgir incompatibilidade com outros pacotes não rodando o software.

**Comment by robson-alcantara** [comment]
adiciona as linhas abaixo no Gemfile:

	gem 'fog-brightbox', '0.16.1'
	gem 'dry-inflector', '0.1.2'
