### ISSUE TITLE
Envio de avaliações não funciona

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-diario#74]
**MENU:**

Envio de avaliações

**DESCRIÇÃO:**

Após atualizar para a versão 1.3.3 o envio de avaliações parou de funcionar. Não sai de 0% e escreve apenas umas duas linhas no log conforme a linha abaixo:

**OBSERVAÇÕES:**

2021-06-02T22:42:29.627Z 3032 TID-1x9gx8 IeducarExamPostingWorker JID-66c8f875edbd04c7b89f1919 INFO: done: 0.646 sec

**AMBIENTE:**

- Plataforma utilizada: instalação direta

**Comment by kesllan** [comment]
Comigo está acontecendo a mesma coisa. Só funciona o envio de Avaliações Conceituais e Descritivas.
Já o envio de Faltas, Avaliações Numéricas e Recuperação de etapas permanecem sempre em 0%.
Segue imagem dos processos no painel web do sidekiq: https://drive.google.com/file/d/1HMHanx1gs8-sxQPTcuq4C-n6NrrYRWdx/view?usp=sharing

**Comment by kesllan** [comment]
Fui no banco de dados na tabela "ieducar_api_exam_postings" e alterei o status para "completed" e o foi apresentando a seguinte mensagem no i-diário: ![photo5051089047602178753](https://user-images.githubusercontent.com/47616123/121701091-ec228800-caa6-11eb-99c9-6ded66495e4d.jpg)

**Comment by kesllan** [comment]
resolvido:
**1º pare a execução do sidekiq com o comando:**

> ps -ef | grep sidekiq | grep -v grep | awk '{print $2}' | xargs kill -TERM && sleep 20

**2º Edite o arquivo config/secrets.yml acrescentando as linhas:**

> sidekiq_password: (seu_password)
> EXAM_POSTING_QUEUES: 'exam_posting_1,exam_posting_2'

**3º Execute os comandos para criar as filas do sidekiq:**

> bundle exec sidekiq -q synchronizer_enqueue_next_job -c 1 -d --logfile log/sidekiq.log
> bundle exec sidekiq -c 10 -d --logfile log/sidekiq.log
> bundle exec sidekiq -q exam_posting_1 -c 1 -d --logfile log/sidekiq_exam_posting_1.log
> bundle exec sidekiq -q exam_posting_2 -c 1 -d --logfile log/sidekiq_exam_posting_1.log

**4º Execute o comando para criar a fila CRITICAL:**

> bundle exec sidekiq -q critical -c 1 -d --logfile log/critical.log

**5º acesse a tabela "ieducar_api_exam_postings" no BD e destrave o botão de enviar, alterando o status de "started" para "completed"**

**6º acesse o painel web do sidekiq em http://dominio_idiario/sidekiq e apaguei os processos "Em espera"**

7º Acesse o i-diário e clique em Enviar novamente. PRONTO.

**Comment by robson-alcantara** [comment]
Qual o login e senha do painel do sidekiq?

**Comment by ArthurLucasDev** [comment]
fiz todas as etapas a cima não carregava o não saia de zero agor meu erro é chega em 99% e da Erro: Chave de acesso inválida!

![image](https://github.com/user-attachments/assets/d0743938-0cf5-476d-8114-fbb1d57aa219)
![image](https://github.com/user-attachments/assets/06342684-c411-4b7c-bf25-d9ff3d2b3952)

ERRO:
 args: [2, 66, {"etapa"=>3, "resource"=>"faltas-por-componente", "faltas"=>{"4"=>{"350"=>{"3"=>{"valor"=>0, "area_do_conhecimento"=>nil}}}}}, {"classroom"=>"4", "student"=>"350", "discipline"=>"3"}, "critical", 0], error: Turma: A2;<br>Aluno: SALATIEL TORRES CARDOSO;<br>Componente curricular: REDAÇÃO;<br> Erro: Chave de acesso inválida!

**Comment by edersoares** [comment]
@ArthurLucasDev você precisa sincronizar a chave que tem no i-Educar na tela de Configurações de Sistema.

https://ieducar.test/configuracoes/configuracoes-de-sistema

Copiar os campos `Chave de acesso ao i-Educar` e `Chave secreta do i-Educar` e colocar no i-Diário na tela de API de integração.

https://idiario.test/api-de-integracao/editar

**Comment by ArthurLucasDev** [comment]
Bom dia! @edersoares a chaves ja estão iguias no i-Diario e no i-Educar tanto que consigo sincronizar os dados do i-Educar para i-Diario, oq não comsigo e enviar faltas e notas 

![image](https://github.com/user-attachments/assets/12362587-b035-43b7-b792-5b6f9a5624e8)
![image](https://github.com/user-attachments/assets/97516572-9d24-4cff-b6fd-f908098be34e)


banco

69	1	"absence"	"error"	1	3		"Ocorreu um erro ao efetuar o envio. Entre em contato com o administrador."	false	"2024-08-28 14:17:24.447298"	"2024-08-28 14:20:10.893764"	"{}"		"args: [2, 69, {""etapa""=>3, ""resource""=>""faltas-por-componente"", ""faltas""=>{""6""=>{""373""=>{""4""=>{""valor""=>0, ""area_do_conhecimento""=>nil}}}}}, {""classroom""=>""6"", ""student""=>""373"", ""discipline""=>""4""}, ""critical"", 0], error: Turma: B2;<br>Aluno: LETÍCIA TELES RODRIGUES;<br>Componente curricular: PORTUGUÊS;<br> Erro: Chave de acesso inválida!"	4




os links que vc enviou não funcionão

**Comment by edersoares** [comment]
@ArthurLucasDev esse erro ocorre nesta parte do i-Educar

https://github.com/portabilis/i-educar/blob/f3390fa5807140ce21e085d7d1439f7738738a75/ieducar/lib/Portabilis/Controller/ApiCoreController.php#L45-L52

Procure entender porque está acontecendo.
