### ISSUE TITLE
Boletim do professor não funciona

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-diario#76]
**MENU:**

Relatórios -> Boletim do professor

**DESCRIÇÃO:**

Ao tentar gerar o relatório, o mesmo não é gerado e o sistema é redirecionado para a página de configuração da API

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Outros detalhes importantes: i-Diario 1.3.3

**Comment by kesllan** [comment]
Mesma coisa acontecendo aqui comigo. Mesma versão e ambiente.

**Comment by robson-alcantara** [comment]
Aqui tem a solução: https://forum.ieducar.org/t/i-diario-resolvido-boletim-do-professor-nao-e-gerado/1423

Quando eu tiver um tempo publico no código fonte para as versões futuras.

**Comment by marcosoliveirasoares94** [comment]
@edersoares, essa issue deve ser fechada e tratada no i-Educar, para isso, já tem um issue aberta https://github.com/portabilis/i-educar/issues/771

**Comment by edersoares** [comment]
@robson-alcantara na release [2.6.2](https://github.com/portabilis/i-educar/releases/tag/2.6.2) foi corrigido o problema, consegue validar pra nós?

**Comment by robson-alcantara** [comment]
Oi @edersoares , infelizmente no momento só irei trabalhar com esta versão nas férias escolares. Mas como já tem uma issue no github do i-educar, vou fechar essa
