### ISSUE TITLE
Como fazer funcionar o módulo de Acompanhamento Pedagógico?

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-diario#78]
**MENU:**

Acompanhamento pedagógico

**DESCRIÇÃO:**

Como fazer funcionar o módulo de Acompanhamento Pedagógico?

**OBSERVAÇÕES:**

A data da última atualização que é exibida é a data de instalação do sistema

**AMBIENTE:**

- Plataforma utilizada (p.ex. Docker, instalação direta):
- Sistema operacional e versão (p.ex. Ubuntu 16.04, Windows 7):
- Navegador e versão (p.ex. Chrome 35.9.9.9):
- Outros detalhes importantes:

**Comment by robson-alcantara** [comment]
Criando um job no cron é possível atualizar as materializeds view: mvw_content_record_by_school_classroom_teachers e mvw_frequency_by_school_classroom_teachers

https://stackoverflow.com/questions/29437650/how-can-i-ensure-that-a-materialized-view-is-always-up-to-date
https://crontab.guru/#0_*_*_*_*
https://serverfault.com/questions/786057/how-do-i-include-the-password-for-the-user-postgres-in-a-maintenance-script

**Comment by kesllan** [comment]
@robson-alcantara seria possível detalhar aqui como você fez para funcionar e atualizar automáticamente? Não consegui entender nos links compartilhados.

**Comment by robson-alcantara** [comment]
Oi @kesllan , segue:

digitei "crontrab -e" no computador/vps que está o idiario e no final do arquivo adicionei as duas linhas abaixo

0 0 * * * PGPASSWORD="<senha do usuário do banco>" psql --username "<nome do usuário do banco>" -d <nome do banco de dados do idiario> -c "REFRESH MATERIALIZED VIEW mvw_frequency_by_school_classrclassroom_teachers"
0 1 * * * PGPASSWORD="<senha do usuário do banco>" psql --username "<nome do usuário do banco>" -d <nome do banco de dados do idiario> -c "REFRESH MATERIALIZED VIEW mvw_content_record_by_school_classroom_teachers"
