### ISSUE TITLE
Percentual de preenchimento de frequência e conteúdo no acompanhamento pedagógico está passando de 100%

### ISSUE THREAD

**Issue by williamsla** [portabilis/i-diario#81]
**MENU:**

Acompanhamento pedagógico -> Filtra uma escola

**DESCRIÇÃO:**

O percentual de preenchimento de frequência e conteúdos de uma turma está passando de 100%
![image](https://user-images.githubusercontent.com/5889193/126880933-92492c13-0ab6-4265-868e-9d8341d3faa8.png)

![image](https://user-images.githubusercontent.com/5889193/126880960-b047058b-1316-4f1e-8095-c66334dc91f7.png)

**OBSERVAÇÕES:**

Observações em geral sobre o problema apontado.

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: Ubuntu 18.04
- Navegador e versão: Chrome Versão 92.0.4515.107 (Versão oficial) 64 bits
- Versão do i-Diário: 1.3.3
- Versão do i-Educar: 2.6.1

**Comment by gustavomendess** [comment]
Boa noite @williamsla, tudo bem?

Subimos alguns patch's para a comunidade que acredito ter resolvido o seu problema, pode, por gentileza, validar e me dar um parecer?

**Comment by williamsla** [comment]
Olá @gustavomendess ! Funcionou. Muito obrigado!
