### ISSUE TITLE
Incluir Observações Gerais

### ISSUE THREAD

**Issue by kesllan** [portabilis/i-diario#93]
Olá comunidade! Gostaria de sugerir uma melhoria para o i-diario. Que fosse criado uma tela para inserção de OBSERVAÇÕES GERAIS por escola. E que funcionasse tipo um uqadro de aviso. Já aparecesse na primeira tela.

**CONTEXTO:**

Por que esta alteração é importante? seria importante para notificar as escolas quanto informações importantes da SME/SRE. Como você usaria isto? Também seria útil para alertar os professores quanto a prazos, lembrar de reuniões, etc. Como esta alteração
pode beneficiar outros usuários? Melhoraria a comunicação interna.

* Atualmente o diário conta com a funcionalidade "Diário de Observações" Mas as mesmas são para observações para aluno ou turma. Não é geral e nem notifica na tela inicial.

**Comment by gustavomendess** [comment]
Bom dia @kesllan, tudo bem?

Muito obrigado pela sua contribuição, realmente é uma melhoria muito legal e que ajudaria muito no sistema, mas hoje não temos ela no nosso roadmap interno de futuras melhorias.

Muito obrigado novamente pela sua contribuição, fique a vontade de enviar um PR para o projeto, ficaria muito feliz em analisar sua proposta. o/
