### ISSUE TITLE
ERRO SINCRONIZAÇÃO IDIARIO - uninitialized constant ClassroomsSynchronizer::Label

### ISSUE THREAD

**Issue by kesllan** [portabilis/i-diario#94]
**MENU:**

Configurações / API de integração

**DESCRIÇÃO:**

Ao clicar no botão "Sincronizar" ou "Sincronização completa" gera o seguinte erro:
**uninitialized constant ClassroomsSynchronizer::Label**

**OBSERVAÇÕES:**

No Fórum algumas pessoas conseguiram resolver o problema removendo os caracteres especias de  cursos, turmas e séries. Porém não deixa de ser um bug a ser resolvido.

Ate onde consegui constatar nos teste.

Funciona com as versões
i-Educar = 2.6.8
i-Diário = 1.3.3

Funciona porém da erro na sincronização devido as acentuações e caracteres especiais em “Cursos, Séries, Turmas e Séries da Escola”
i-Educar = 2.6.8
i-Diário = 1.3.5

**AMBIENTE:**

- Instalação direta
- Ubuntu 20.04:
- Chrome Versão 99.0.4844.74
- i-diario versão 1.3.5
- i-educar 2.6.8

![image (1)](https://user-images.githubusercontent.com/47616123/159004335-f46fe7a5-9bb6-4ee7-99f6-abc37f7750fd.png)
![image](https://user-images.githubusercontent.com/47616123/159004338-01197b8e-9cb1-492d-bcfa-cc2719b8bcc8.png)

**Comment by marcosoliveirasoares94** [comment]
@kesllan obrigado pela abertura da issue, mencionei ela no Fórum para rastreabilidade.

@gustavomendess, realizei uma conferência nas mesclagem e a versão atual 1.3.5 realmente não realiza a sincronização quando Cursos, Séries, Séries da Escola e Turmas possuem caracteres especiais no nome, no entanto a versão 1.3.3 funciona, poderia dar uma atenção assim que possível dessa forma possibilitando o uso da versão 1.3.5 pela comunidade ?

Não entendo muito dessa linguagem, porém pelo histórico de modificações, tem relação com esse arquivo: `app/services/ieducar_synchronizers/classrooms_synchronizer.rb`

**Comment by gustavomendess** [comment]
Boa noite @kesllan @marcosoliveirasoares94, tudo bem?


Na próxima Sexta-feira irei subir mais um patch para a comunidade, já com esse problema resolvido, tranquilo?

**Comment by marcosoliveirasoares94** [comment]
Obrigado pelo retorno @gustavomendess.

**Comment by gustavomendess** [comment]
Boa noite @marcosoliveirasoares94, tudo bem?

A solução do problema em questão foi corrigido na nova release: https://github.com/portabilis/i-diario/releases/tag/1.3.6

Qualquer dúvida fico a disposição!

**Comment by kesllan** [comment]
> Boa noite @kesllan @marcosoliveirasoares94, tudo bem?
> 
> Na próxima Sexta-feira irei subir mais um patch para a comunidade, já com esse problema resolvido, tranquilo?

Cara! Muito obrigado mesmo por resolver o problema. Em nome da comunidade eu agradeço.

**Comment by marcosoliveirasoares94** [comment]
> Boa noite @marcosoliveirasoares94, tudo bem?
> 
> A solução do problema em questão foi corrigido na nova release: https://github.com/portabilis/i-diario/releases/tag/1.3.6
> 
> Qualquer dúvida fico a disposição!

Obrigado pelo retorno @gustavomendess!
Agradeço em nome da comunidade do i-Educar pela contribuição que viabiliza a implantação das versões mais novas do i-Educar e i-Diário.

Irei mencionar no post do Fórum do i-Educar qual a versão que corrigiu o problema.
